AWSTemplateFormatVersion: '2010-09-09'  
  StackName: FastAWSConnectionsVpc
  Description: This cloudformation template creates a VPC
  Parameters:
  - ParameterKey: CompanyName
    ParameterValue: Veloe
  - ParameterKey: AccountSetupStack
    ParameterValue: VeloeAccountSetup
  - ParameterKey: Az2
    ParameterValue: us-east-1d
  - ParameterKey: Environment
    ParameterValue: Dev
  - ParameterKey: Az1
    ParameterValue: us-east-1c
  - ParameterKey: Route53HostedZoneDomain
    ParameterValue: local.veloe.com.br
  Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 172.31.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        InstanceTenancy: default
    InternetGateway:
      Type: AWS::EC2::InternetGateway

    VPCGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref VPC
        InternetGatewayId: !Ref InternetGateway
    
    SubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1a
        VpcId: !Ref VPC
        CidrBlock: 172.31.0.0/20
        MapPublicIpOnLaunch: true
    SubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1b
        VpcId: !Ref VPC
        CidrBlock: 172.31.16.0/20
        MapPublicIpOnLaunch: true
    SubnetC:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: us-east-1c
        VpcId: !Ref VPC
        CidrBlock: 172.31.32.0/20
        MapPublicIpOnLaunch: true




#https://sookocheff.com/post/aws/how-to-create-a-vpc-using-cloudformation/
  